TRUNCATE TABLE OCULAR_DATASET;
INSERT INTO OCULAR_DATASET (DIAGNOSTIC_KEYWORDS_ID,IMG_FILENAME,OCULAR_TYPE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,DOWNLOAD_FILE_STATUS,IMGNAME)
SELECT DISTINCT DIAGNOSTIC_KEYWORDS_ID , 
CASE WHEN DIAGNOSTIC_KEYWORDS_ID = 1 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Normal/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 2 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Diabetes/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 3 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Glaucoma/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 4 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Age related Macular Degeneration/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 5 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Hypertension/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 6 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Pathological Myopia/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 7 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Other diseases or abnormalities/",IMAGE_NAME)
     WHEN DIAGNOSTIC_KEYWORDS_ID = 8 THEN CONCAT("https://stretina.s3.ap-southeast-1.amazonaws.com/dataset/Cataract/",IMAGE_NAME)
END AS IMG_FILENAME
     , SIDE AS OCULAR_TYPE
     , NULL AS CREATE_DATE 
     , NULL AS CREATE_USER
     , NULL AS UPDATE_DATE
     , NULL AS UPDATE_USER
     , NULL AS DOWNLOAD_FILE_STATUS
     , IMAGE_NAME AS IMGNAME
FROM (
SELECT CASE WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('normal fundus','normal fundus，lens dust','lens dust，normal fundus','normal fundus，normal fundus') 
			THEN 1 
			WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('laser spot，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy'
                ,'macular epiretinal membrane，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，laser spot'
                ,'moderate non proliferative retinopathy，myelinated nerve fibers'
                ,'diabetic retinopathy'
                ,'laser spot，white vessel，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，cataract'
                ,'moderate non proliferative retinopathy，retina fold'
                ,'severe nonproliferative retinopathy，white vessel'
                ,'moderate non proliferative retinopathy，epiretinal membrane'
                ,'epiretinal membrane，mild nonproliferative retinopathy'
                ,'macular epiretinal membrane，moderate non proliferative retinopathy'
                ,'severe nonproliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy，epiretinal membrane'
                ,'mild nonproliferative retinopathy，myelinated nerve fibers'
                ,'lens dust，moderate non proliferative retinopathy'
                ,'mild nonproliferative retinopathy，epiretinal membrane over the macula'
                ,'mild nonproliferative retinopathy，macular epiretinal membrane'
                ,'severe nonproliferative retinopathy'
                ,'epiretinal membrane，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，lens dust'
                ,'white vessel，severe nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，branch retinal vein occlusion'
                ,'moderate non proliferative retinopathy，drusen'
                ,'mild nonproliferative retinopathy，drusen'
                ,'white vessel，moderate non proliferative retinopathy'
                ,'macular epiretinal membrane，severe nonproliferative retinopathy'
                ,'laser spot，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，macular epiretinal membrane'
                ,'mild nonproliferative retinopathy，vitreous degeneration'
                ,'vitreous degeneration，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，chorioretinal atrophy'
                ,'laser spot，moderate non proliferative retinopathy，macular epiretinal membrane'
                ,'mild nonproliferative retinopathy，retinal pigmentation'
                ,'moderate non proliferative retinopathy，white vessel'
                ,'mild nonproliferative retinopathy，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，optic disc edema'
                ,'moderate non proliferative retinopathy，vitreous degeneration'
                ,'macular epiretinal membrane，moderate non proliferative retinopathy，laser spot'
                ,'myelinated nerve fibers，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，atrophic change'
                ,'diabetic retinopathy，wet age-related macular degeneration'
                ,'lens dust，mild nonproliferative retinopathy，myelinated nerve fibers'
                ,'diabetic retinopathy，post laser photocoagulation'
                ,'moderate non proliferative retinopathy，glaucoma'
                ,'suspected moderate non proliferative retinopathy，pathological myopia'
                ,'moderate non proliferative retinopathy，pathological myopia'
                ,'diabetic retinopathy，dry age-related macular degeneration'
                ,'diabetic retinopathy，wet age-related macular degeneration，macular epiretinal membrane'
                ,'moderate non proliferative retinopathy，refractive media opacity'
                ,'mild nonproliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy，dry age-related macular degeneration'
                ,'epiretinal membrane，moderate non proliferative retinopathy，laser spot'
                ,'moderate non proliferative retinopathy，myelinated nerve fibers，laser spot'
                ,'moderate non proliferative retinopathy，suspected glaucoma'
                ,'moderate non proliferative retinopathy，abnormal pigment '
                ,'macular epiretinal membrane，diabetic retinopathy'
                ,'moderate non proliferative retinopathy，retinitis pigmentosa'
                ,'epiretinal membrane over the macula，moderate non proliferative retinopathy，lens dust'
                ,'moderate non proliferative retinopathy，spotted membranous change'
                ,'macular epiretinal membrane，lens dust，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，laser spot，lens dust'
                ,'moderate non proliferative retinopathy，epiretinal membrane over the macula'
                ,'moderate non proliferative retinopathy，central retinal artery occlusion'
                ,'moderate non proliferative retinopathy，moderate non proliferative retinopathy，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，post laser photocoagulation'
                ,'moderate non proliferative retinopathy，retinal pigment epithelial hypertrophy'
                ,'moderate non proliferative retinopathy，laser spot，epiretinal membrane'
                ,'myelinated nerve fibers，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，old branch retinal vein occlusion'
                ,'macular epiretinal membrane，severe nonproliferative retinopathy，old branch retinal vein occlusion'
                ,'macular epiretinal membrane，laser spot，lens dust，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，tessellated fundus'
                ,'mild nonproliferative retinopathy，glaucoma，vitreous degeneration'
                ,'diabetic retinopathy，macular epiretinal membrane'
                ,'moderate non proliferative retinopathy，age-related macular degeneration'
                ,'laser spot，moderate non proliferative retinopathy，white vessel'
                ,'lens dust，mild nonproliferative retinopathy'
                ,'white vessel，mild nonproliferative retinopathy'
                ,'optic disk photographically invisible，diabetic retinopathy'
                ,'post retinal laser surgery，moderate non proliferative retinopathy'
			    ) THEN 2 
            WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('proliferative diabetic retinopathy，hypertensive retinopathy'
                ,'laser spot，severe proliferative diabetic retinopathy'
                ,'laser spot，proliferative diabetic retinopathy，white vessel'
                ,'severe proliferative diabetic retinopathy'
                ,'epiretinal membrane，laser spot，severe proliferative diabetic retinopathy'
                ,'proliferative diabetic retinopathy'
                ,'severe proliferative diabetic retinopathy，laser spot'
                ,'white vessel，proliferative diabetic retinopathy，suspected microvascular anomalies'
                ) THEN 2
            WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('suspected glaucoma'
                ,'glaucoma'
                ,'suspected glaucoma，suspicious diabetic retinopathy'
                ,'suspected glaucoma，moderate non proliferative retinopathy'
                ,'glaucoma，optic nerve atrophy'
                ,'glaucoma，myopia retinopathy'
                ,'glaucoma，macular epiretinal membrane'
                ,'glaucoma，diabetic retinopathy'
                ,'glaucoma，diffuse retinal atrophy'
                ,'glaucoma，intraretinal hemorrhage'
                ,'glaucoma，hypertensive retinopathy'
                ,'glaucoma，central retinal vein occlusion'
                ,'macular epiretinal membrane，glaucoma'
                ,'suspected glaucoma，refractive media opacity'
                ,'suspected glaucoma，mild nonproliferative retinopathy'
                ,'white vessel，suspected glaucoma'
                ,'suspected glaucoma，drusen'
                ,'glaucoma，moderate non proliferative retinopathy'
                ,'lens dust，glaucoma'
                ,'glaucoma，lens dust'
                ,'myelinated nerve fibers，suspected glaucoma'
                ,'glaucoma，mild nonproliferative retinopathy，macular pigmentation disorder'
                ,'glaucoma，wet age-related macular degeneration'
                ,'glaucoma，old central retinal vein occlusion'
                ,'glaucoma，fundus laser photocoagulation spots'
                ,'myelinated nerve fibers，glaucoma'
                ,'epiretinal membrane，lens dust，glaucoma'
                ,'glaucoma，moderate non proliferative retinopathy，laser spot'
                ) THEN 3
            WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('drusen'
                ,'wet age-related macular degeneration'
                ,'dry age-related macular degeneration'
                ,'retinitis pigmentosa'
                ,'retinal pigment epithelium atrophy，diabetic retinopathy'
                ,'retinal pigmentation'
                ,'dry age-related macular degeneration，glaucoma'
                ,'dry age-related macular degeneration，diabetic retinopathy'
                ,'depigmentation of the retinal pigment epithelium'
                ,'maculopathy，macular epiretinal membrane'
                ,'myopic maculopathy'
                ,'drusen，cataract，lens dust'
                ,'maculopathy'
                ,'epiretinal membrane，drusen'
                ,'lens dust，drusen'
                ,'drusen，branch retinal vein occlusion'
                ,'wet age-related macular degeneration，diffuse chorioretinal atrophy'
                ,'drusen，mild nonproliferative retinopathy'
                ,'dry age-related macular degeneration，myopia retinopathy'
                ,'dry age-related macular degeneration，hypertensive retinopathy'
                ,'dry age-related macular degeneration，choroidal nevus'
                ,'maculopathy，glaucoma'
                ,'wet age-related macular degeneration，myopia retinopathy'
                ,'wet age-related macular degeneration，diabetic retinopathy'
                ,'drusen，atrophic change'
                ,'wet age-related macular degeneration，hypertensive retinopathy'
                ,'drusen，drusen'
                ,'dry age-related macular degeneration，macular epiretinal membrane'
                ,'drusen，epiretinal membrane'
                ,'drusen，vitreous degeneration'
                ,'drusen，moderate non proliferative retinopathy，lens dust'
                ,'dry age-related macular degeneration，post laser photocoagulation'
                ,'drusen，moderate non proliferative retinopathy'
                ,'macular epiretinal membrane，drusen'
                ,'wet age-related macular degeneration，glaucoma'
                ,'myelinated nerve fibers，lens dust，drusen'
                ,'myelinated nerve fibers，drusen'
                ,'retinal pigment epithelial hypertrophy，moderate non proliferative retinopathy'
                ) THEN 4
                WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('hypertensive retinopathy'
                ,'hypertensive retinopathy,diabetic retinopathy'
                ,'hypertensive retinopathy，optic nerve atrophy'
                ,'hypertensive retinopathy，suspected glaucoma'
                ,'hypertensive retinopathy，mild nonproliferative retinopathy'
                ,'hypertensive retinopathy，suspected diabetic retinopathy'
                ,'hypertensive retinopathy，moderate non proliferative retinopathy'
                ,'hypertensive retinopathy，cataract'
                ,'hypertensive retinopathy，diabetic retinopathy'
                ,'hypertensive retinopathy，age-related macular degeneration'
                ,'hypertensive retinopathy，macular epiretinal membrane'
                ,'hypertensive retinopathy，branch retinal vein occlusion'
                ,'hypertensive retinopathy，maculopathy'
                ,'hypertensive retinopathy，branch retinal vein occlusion，vitreous opacity'
                ) THEN 5
                WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('pathological myopia'
                ,'chorioretinal atrophy'
                ,'chorioretinal atrophy'
                ,'chorioretinal atrophy with pigmentation proliferation，lens dust'
                ,'epiretinal membrane，chorioretinal atrophy'
                ,'refractive media opacity，pathological myopia'
                ,'lens dust，pathological myopia'
                ,'tessellated fundus，chorioretinal atrophy'
                ,'laser spot，chorioretinal atrophy，glaucoma'
                ,'pathological myopia，lens dust'
                ,'pathological myopia，moderate non proliferative retinopathy'
                ,'pathological myopia，suspected macular epimacular membrane'
                ,'chorioretinal atrophy，epiretinal membrane'
                ,'myopia retinopathy'
                ,'lens dust，chorioretinal atrophy'
                ) THEN 6 
                WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('cataract'
                ,'cataract，lens dust'
                ,'cataract，suspected glaucoma'
                ,'cataract，moderate non proliferative retinopathy'
                ,'cataract，myelinated nerve fibers，moderate non proliferative retinopathy'
                ,'laser spot，cataract'
                ,'cataract，mild nonproliferative retinopathy'
                ,'lens dust，cataract'
                ,'cataract，branch retinal vein occlusion'
                ,'cataract，suspected cataract'
                ,'cataract，laser spot'
                ,'cataract，laser spot，moderate non proliferative retinopathy'
                ,'cataract，vitreous degeneration'
                ) THEN 8 
                WHEN TRIM(LEFT_DIAGNOSTIC_KEYWORDS) IN ('macular hole'
                ,'vitreous degeneration'
                ,'branch retinal vein occlusion'
                ,'myelinated nerve fibers'
                ,'refractive media opacity'
                ,'spotted membranous change'
                ,'central retinal vein occlusion'
                ,'suspected retinal vascular sheathing'
                ,'tessellated fundus'
                ,'macular coloboma'
                ,'wedge white line change'
                ,'laser spot'
                ,'chorioretinal atrophy with pigmentation proliferation'
                ,'pigment epithelium proliferation'
                ,'optic disk photographically invisible'
                ,'old chorioretinopathy'
                ,'old branch retinal vein occlusion'
                ,'idiopathic choroidal neovascularization'
                ,'silicone oil eye'
                ,'optic disc edema'
                ,'image offset'
                ,'old central retinal vein occlusion'
                ,'fundus laser photocoagulation spots'
                ,'peripapillary atrophy'
                ,'anterior segment image'
                ,'low image quality'
                ,'no fundus image'
                ,'low image quality,maculopathy'
                ,'branch retinal artery occlusion'
                ,'central retinal artery occlusion'
                ,'abnormal pigment '
                ,'oval yellow-white atrophy'
                ,'retinochoroidal coloboma'
                ,'congenital choroidal coloboma'
                ,'morning glory syndrome'
                ,'glial remnants anterior to the optic disc'
                ,'atrophic change'
                ,'optic discitis'
                ,'retinal vascular sheathing'
                ,'retina fold'
                ,'suspected abnormal color of  optic disc'
                ,'pigmentation disorder'
                ,'central serous chorioretinopathy'
                ,'post retinal laser surgery'
                ,'intraretinal microvascular abnormality'
                ) THEN 7 END AS DIAGNOSTIC_KEYWORDS_ID
            , LEFT_DIAGNOSTIC_KEYWORDS AS RAW_DIAGNOSTIC
            , LEFT_FUNDUS AS IMAGE_NAME
            , 0 AS SIDE
FROM RAW_OCULAR_DATASET rod 
UNION ALL 
SELECT CASE WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('normal fundus','normal fundus，lens dust','lens dust，normal fundus','normal fundus，normal fundus') 
			THEN 1 
			WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('laser spot，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy'
                ,'macular epiretinal membrane，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，laser spot'
                ,'moderate non proliferative retinopathy，myelinated nerve fibers'
                ,'diabetic retinopathy'
                ,'laser spot，white vessel，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，cataract'
                ,'moderate non proliferative retinopathy，retina fold'
                ,'severe nonproliferative retinopathy，white vessel'
                ,'moderate non proliferative retinopathy，epiretinal membrane'
                ,'epiretinal membrane，mild nonproliferative retinopathy'
                ,'macular epiretinal membrane，moderate non proliferative retinopathy'
                ,'severe nonproliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy，epiretinal membrane'
                ,'mild nonproliferative retinopathy，myelinated nerve fibers'
                ,'lens dust，moderate non proliferative retinopathy'
                ,'mild nonproliferative retinopathy，epiretinal membrane over the macula'
                ,'mild nonproliferative retinopathy，macular epiretinal membrane'
                ,'severe nonproliferative retinopathy'
                ,'epiretinal membrane，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，lens dust'
                ,'white vessel，severe nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，branch retinal vein occlusion'
                ,'moderate non proliferative retinopathy，drusen'
                ,'mild nonproliferative retinopathy，drusen'
                ,'white vessel，moderate non proliferative retinopathy'
                ,'macular epiretinal membrane，severe nonproliferative retinopathy'
                ,'laser spot，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，macular epiretinal membrane'
                ,'mild nonproliferative retinopathy，vitreous degeneration'
                ,'vitreous degeneration，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，chorioretinal atrophy'
                ,'laser spot，moderate non proliferative retinopathy，macular epiretinal membrane'
                ,'mild nonproliferative retinopathy，retinal pigmentation'
                ,'moderate non proliferative retinopathy，white vessel'
                ,'mild nonproliferative retinopathy，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，optic disc edema'
                ,'moderate non proliferative retinopathy，vitreous degeneration'
                ,'macular epiretinal membrane，moderate non proliferative retinopathy，laser spot'
                ,'myelinated nerve fibers，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，atrophic change'
                ,'diabetic retinopathy，wet age-related macular degeneration'
                ,'lens dust，mild nonproliferative retinopathy，myelinated nerve fibers'
                ,'diabetic retinopathy，post laser photocoagulation'
                ,'moderate non proliferative retinopathy，glaucoma'
                ,'suspected moderate non proliferative retinopathy，pathological myopia'
                ,'moderate non proliferative retinopathy，pathological myopia'
                ,'diabetic retinopathy，dry age-related macular degeneration'
                ,'diabetic retinopathy，wet age-related macular degeneration，macular epiretinal membrane'
                ,'moderate non proliferative retinopathy，refractive media opacity'
                ,'mild nonproliferative retinopathy，hypertensive retinopathy'
                ,'mild nonproliferative retinopathy，dry age-related macular degeneration'
                ,'epiretinal membrane，moderate non proliferative retinopathy，laser spot'
                ,'moderate non proliferative retinopathy，myelinated nerve fibers，laser spot'
                ,'moderate non proliferative retinopathy，suspected glaucoma'
                ,'moderate non proliferative retinopathy，abnormal pigment '
                ,'macular epiretinal membrane，diabetic retinopathy'
                ,'moderate non proliferative retinopathy，retinitis pigmentosa'
                ,'epiretinal membrane over the macula，moderate non proliferative retinopathy，lens dust'
                ,'moderate non proliferative retinopathy，spotted membranous change'
                ,'macular epiretinal membrane，lens dust，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，laser spot，lens dust'
                ,'moderate non proliferative retinopathy，epiretinal membrane over the macula'
                ,'moderate non proliferative retinopathy，central retinal artery occlusion'
                ,'moderate non proliferative retinopathy，moderate non proliferative retinopathy，moderate non proliferative retinopathy'
                ,'moderate non proliferative retinopathy，post laser photocoagulation'
                ,'moderate non proliferative retinopathy，retinal pigment epithelial hypertrophy'
                ,'moderate non proliferative retinopathy，laser spot，epiretinal membrane'
                ,'myelinated nerve fibers，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，old branch retinal vein occlusion'
                ,'macular epiretinal membrane，severe nonproliferative retinopathy，old branch retinal vein occlusion'
                ,'macular epiretinal membrane，laser spot，lens dust，mild nonproliferative retinopathy'
                ,'moderate non proliferative retinopathy，tessellated fundus'
                ,'mild nonproliferative retinopathy，glaucoma，vitreous degeneration'
                ,'diabetic retinopathy，macular epiretinal membrane'
                ,'moderate non proliferative retinopathy，age-related macular degeneration'
                ,'laser spot，moderate non proliferative retinopathy，white vessel'
                ,'lens dust，mild nonproliferative retinopathy'
                ,'white vessel，mild nonproliferative retinopathy'
                ,'optic disk photographically invisible，diabetic retinopathy'
                ,'post retinal laser surgery，moderate non proliferative retinopathy'
			    ) THEN 2 
            WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('proliferative diabetic retinopathy，hypertensive retinopathy'
                ,'laser spot，severe proliferative diabetic retinopathy'
                ,'laser spot，proliferative diabetic retinopathy，white vessel'
                ,'severe proliferative diabetic retinopathy'
                ,'epiretinal membrane，laser spot，severe proliferative diabetic retinopathy'
                ,'proliferative diabetic retinopathy'
                ,'severe proliferative diabetic retinopathy，laser spot'
                ,'white vessel，proliferative diabetic retinopathy，suspected microvascular anomalies'
                ) THEN 2
            WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('suspected glaucoma'
                ,'glaucoma'
                ,'suspected glaucoma，suspicious diabetic retinopathy'
                ,'suspected glaucoma，moderate non proliferative retinopathy'
                ,'glaucoma，optic nerve atrophy'
                ,'glaucoma，myopia retinopathy'
                ,'glaucoma，macular epiretinal membrane'
                ,'glaucoma，diabetic retinopathy'
                ,'glaucoma，diffuse retinal atrophy'
                ,'glaucoma，intraretinal hemorrhage'
                ,'glaucoma，hypertensive retinopathy'
                ,'glaucoma，central retinal vein occlusion'
                ,'macular epiretinal membrane，glaucoma'
                ,'suspected glaucoma，refractive media opacity'
                ,'suspected glaucoma，mild nonproliferative retinopathy'
                ,'white vessel，suspected glaucoma'
                ,'suspected glaucoma，drusen'
                ,'glaucoma，moderate non proliferative retinopathy'
                ,'lens dust，glaucoma'
                ,'glaucoma，lens dust'
                ,'myelinated nerve fibers，suspected glaucoma'
                ,'glaucoma，mild nonproliferative retinopathy，macular pigmentation disorder'
                ,'glaucoma，wet age-related macular degeneration'
                ,'glaucoma，old central retinal vein occlusion'
                ,'glaucoma，fundus laser photocoagulation spots'
                ,'myelinated nerve fibers，glaucoma'
                ,'epiretinal membrane，lens dust，glaucoma'
                ,'glaucoma，moderate non proliferative retinopathy，laser spot'
                ) THEN 3
            WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('drusen'
                ,'wet age-related macular degeneration'
                ,'dry age-related macular degeneration'
                ,'retinitis pigmentosa'
                ,'retinal pigment epithelium atrophy，diabetic retinopathy'
                ,'retinal pigmentation'
                ,'dry age-related macular degeneration，glaucoma'
                ,'dry age-related macular degeneration，diabetic retinopathy'
                ,'depigmentation of the retinal pigment epithelium'
                ,'maculopathy，macular epiretinal membrane'
                ,'myopic maculopathy'
                ,'drusen，cataract，lens dust'
                ,'maculopathy'
                ,'epiretinal membrane，drusen'
                ,'lens dust，drusen'
                ,'drusen，branch retinal vein occlusion'
                ,'wet age-related macular degeneration，diffuse chorioretinal atrophy'
                ,'drusen，mild nonproliferative retinopathy'
                ,'dry age-related macular degeneration，myopia retinopathy'
                ,'dry age-related macular degeneration，hypertensive retinopathy'
                ,'dry age-related macular degeneration，choroidal nevus'
                ,'maculopathy，glaucoma'
                ,'wet age-related macular degeneration，myopia retinopathy'
                ,'wet age-related macular degeneration，diabetic retinopathy'
                ,'drusen，atrophic change'
                ,'wet age-related macular degeneration，hypertensive retinopathy'
                ,'drusen，drusen'
                ,'dry age-related macular degeneration，macular epiretinal membrane'
                ,'drusen，epiretinal membrane'
                ,'drusen，vitreous degeneration'
                ,'drusen，moderate non proliferative retinopathy，lens dust'
                ,'dry age-related macular degeneration，post laser photocoagulation'
                ,'drusen，moderate non proliferative retinopathy'
                ,'macular epiretinal membrane，drusen'
                ,'wet age-related macular degeneration，glaucoma'
                ,'myelinated nerve fibers，lens dust，drusen'
                ,'myelinated nerve fibers，drusen'
                ,'retinal pigment epithelial hypertrophy，moderate non proliferative retinopathy'
                ) THEN 4
                WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('hypertensive retinopathy'
                ,'hypertensive retinopathy,diabetic retinopathy'
                ,'hypertensive retinopathy，optic nerve atrophy'
                ,'hypertensive retinopathy，suspected glaucoma'
                ,'hypertensive retinopathy，mild nonproliferative retinopathy'
                ,'hypertensive retinopathy，suspected diabetic retinopathy'
                ,'hypertensive retinopathy，moderate non proliferative retinopathy'
                ,'hypertensive retinopathy，cataract'
                ,'hypertensive retinopathy，diabetic retinopathy'
                ,'hypertensive retinopathy，age-related macular degeneration'
                ,'hypertensive retinopathy，macular epiretinal membrane'
                ,'hypertensive retinopathy，branch retinal vein occlusion'
                ,'hypertensive retinopathy，maculopathy'
                ,'hypertensive retinopathy，branch retinal vein occlusion，vitreous opacity'
                ) THEN 5
                WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('pathological myopia'
                ,'chorioretinal atrophy'
                ,'chorioretinal atrophy'
                ,'chorioretinal atrophy with pigmentation proliferation，lens dust'
                ,'epiretinal membrane，chorioretinal atrophy'
                ,'refractive media opacity，pathological myopia'
                ,'lens dust，pathological myopia'
                ,'tessellated fundus，chorioretinal atrophy'
                ,'laser spot，chorioretinal atrophy，glaucoma'
                ,'pathological myopia，lens dust'
                ,'pathological myopia，moderate non proliferative retinopathy'
                ,'pathological myopia，suspected macular epimacular membrane'
                ,'chorioretinal atrophy，epiretinal membrane'
                ,'myopia retinopathy'
                ,'lens dust，chorioretinal atrophy'
                ) THEN 6 
                WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('cataract'
                ,'cataract，lens dust'
                ,'cataract，suspected glaucoma'
                ,'cataract，moderate non proliferative retinopathy'
                ,'cataract，myelinated nerve fibers，moderate non proliferative retinopathy'
                ,'laser spot，cataract'
                ,'cataract，mild nonproliferative retinopathy'
                ,'lens dust，cataract'
                ,'cataract，branch retinal vein occlusion'
                ,'cataract，suspected cataract'
                ,'cataract，laser spot'
                ,'cataract，laser spot，moderate non proliferative retinopathy'
                ,'cataract，vitreous degeneration'
                ) THEN 8 
                WHEN TRIM(RIGHT_DIAGNOSTIC_KEYWORDS) IN ('macular hole'
                ,'vitreous degeneration'
                ,'branch retinal vein occlusion'
                ,'myelinated nerve fibers'
                ,'refractive media opacity'
                ,'spotted membranous change'
                ,'central retinal vein occlusion'
                ,'suspected retinal vascular sheathing'
                ,'tessellated fundus'
                ,'wedge white line change'
                ,'macular coloboma'
                ,'laser spot'
                ,'chorioretinal atrophy with pigmentation proliferation'
                ,'pigment epithelium proliferation'
                ,'optic disk photographically invisible'
                ,'old chorioretinopathy'
                ,'old branch retinal vein occlusion'
                ,'idiopathic choroidal neovascularization'
                ,'silicone oil eye'
                ,'optic disc edema'
                ,'image offset'
                ,'old central retinal vein occlusion'
                ,'fundus laser photocoagulation spots'
                ,'peripapillary atrophy'
                ,'anterior segment image'
                ,'low image quality'
                ,'low image quality,maculopathy'
                ,'no fundus image'
                ,'branch retinal artery occlusion'
                ,'central retinal artery occlusion'
                ,'abnormal pigment '
                ,'oval yellow-white atrophy'
                ,'retinochoroidal coloboma'
                ,'congenital choroidal coloboma'
                ,'morning glory syndrome'
                ,'glial remnants anterior to the optic disc'
                ,'atrophic change'
                ,'optic discitis'
                ,'retinal vascular sheathing'
                ,'retina fold'
                ,'suspected abnormal color of  optic disc'
                ,'pigmentation disorder'
                ,'central serous chorioretinopathy'
                ,'post retinal laser surgery'
                ,'intraretinal microvascular abnormality'
                ) THEN 7 END AS DIAGNOSTIC_KEYWORDS_ID
            , RIGHT_DIAGNOSTIC_KEYWORDS AS RAW_DIAGNOSTIC
            , RIGHT_FUNDUS AS IMAGE_NAME
            , 1 AS SIDE
FROM RAW_OCULAR_DATASET rod 
) AS TRANSFORM_DATA
WHERE DIAGNOSTIC_KEYWORDS_ID IS NOT NULL ;