version: '3.3'
services:
  health-me-train-model:
    build: 
      context: .
      dockerfile: Dockerfile-local 
    container_name: health-me-train-model2
    hostname: health-me-train-model2
    working_dir: /app
    volumes:
      - ./:/app
    tty: true